name: Pre-commit Hooks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest  # Run the job on the latest Ubuntu

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0 

      # Step 2: Set up Python (needed for pre-commit)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # You can adjust the version as needed

      # Step 3: Install pre-commit
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      # Step 4: Install pre-commit hooks
      - name: Install pre-commit hooks
        run: pre-commit install

      # Step 5: Run pre-commit hooks on all files
      - name: Run pre-commit hooks
        run: pre-commit run --all-files
